version: '2'
services:
  influxdb:
    image: influxdb:1.2.2-alpine
    environment:
      - INFLUXDB_DB=hds
    volumes:
      - ./docker/influxdb:/var/lib/influxdb

  hds:
    image: docker.linksmart.eu/hds
    ports:
      - "8085:8085"
      - "4000:4000"
    depends_on:
      - influxdb
    volumes:
      - ./docker/data:/data
#      - ./conf:/conf

  dummy-stream:
    image: docker.linksmart.eu/hds/dummy-datasource
    depends_on:
      - hds
    command: ["--server", "http://hds:8085"]
