version: '2'
services:
  influxdb:
    image: influxdb:1.5.2-alpine
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    environment:
       - INFLUXDB_DB=hds
#    ports: ["8086:8086"]
    restart: unless-stopped
  hds:
    image: docker.linksmart.eu/hds:snapshot
    ports:
      - "8085:8085"
    depends_on:
      - influxdb
    volumes:
      - ./volumes/hds/data:/data
      # - ./volumes/hds/conf:/conf
    restart: unless-stopped
#    command: ["-conf", "/conf/myconf.json"]
  dummy-stream:
    image: docker.linksmart.eu/hds/dummy-datasource
    # build:
    #   context: .
    depends_on:
      - hds
    command: ["--server", "http://hds:8085"]
